# Generated by Django 5.0.2 on 2025-05-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicrecommendation',
            name='emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
